# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      # Align with Drupal updates.
      day: 'wednesday'
    ignore:
      - dependency-name: 'cypress'
        update-types: ['version-update:semver-patch']
