name: cypress tests

on: [pull_request]

jobs:
  build:
    name: Building site and running cypress tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v4

      - uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          php_extensions: gd

      - name: Install ddev.
        run: |
          curl -fsSL https://apt.fury.io/drud/gpg.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/ddev.gpg > /dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/ddev.gpg] https://apt.fury.io/drud/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list
          sudo apt update && sudo apt install -y ddev

      - name: Setup Drupal website.
        run: ./scripts/setup.sh

      - name: Install cypress dependencies.
        run: yarn install --frozen-lockfile

      - name: Run cypress.
        run: yarn run cy:run

      - name: Publish test results.
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: github.actor != 'dependabot[bot]'
        with:
          files: cypress/*.xml
          check_name: 'Cypress Test Results'

      - name: Archive test results.
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results
          path: cypress
          retention-days: 2

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
